package com.dreamteam.pki.model.enums;

public enum CertificateExtensionType {
    AUTHORITY_INFO_ACCESS,
    AUTHORITY_KEY_IDENTIFIER,
    BASIC_CONSTRAINTS,
    CERTIFICATE_POLICIES_EXT,
    CRL_DISTRIBUTION_POINTS,
    EXT_KEY_USAGE,
    ISSUER_ALT_NAME,
    KEY_USAGE,
    NAME_CONSTRAINTS,
    OCSP_NO_CHECK,
    POLICY_CONSTRAINTS,
    POLICY_MAPPINGS,
    PRIVATE_KEY_USAGE_PERIOD,
    SUBJECT_ALT_NAME,
    SUBJECT_DIRECTORY_ATTRIBUTES,
    SUBJECT_KEY_IDENTIFIER
}
