export enum CertificateExtensionType {
  AUTHORITY_INFO_ACCESS = "AUTHORITY_INFO_ACCESS",
  AUTHORITY_KEY_IDENTIFIER = "AUTHORITY_KEY_IDENTIFIER",
  BASIC_CONSTRAINTS = "BASIC_CONSTRAINTS",
  CERTIFICATE_POLICIES_EXT = "CERTIFICATE_POLICIES_EXT",
  CRL_DISTRIBUTION_POINTS = "CRL_DISTRIBUTION_POINTS",
  EXT_KEY_USAGE = "EXT_KEY_USAGE",
  ISSUER_ALT_NAME = "ISSUER_ALT_NAME",
  KEY_USAGE = "KEY_USAGE",
  NAME_CONSTRAINTS = "NAME_CONSTRAINTS",
  OCSP_NO_CHECK = "OCSP_NO_CHECK",
  POLICY_CONSTRAINTS = "POLICY_CONSTRAINTS",
  POLICY_MAPPINGS = "POLICY_MAPPINGS",
  PRIVATE_KEY_USAGE_PERIOD = "PRIVATE_KEY_USAGE_PERIOD",
  SUBJECT_ALT_NAME = "SUBJECT_ALT_NAME",
  SUBJECT_DIRECTORY_ATTRIBUTES = "SUBJECT_DIRECTORY_ATTRIBUTES",
  SUBJECT_KEY_IDENTIFIER = "SUBJECT_KEY_IDENTIFIER"
}
